version: 1
labels:
- label: "feature"
  title: "^feat(!)?: ([\\w ])+([\\s\\S]*)"
- label: "fix"
  title: "^fix(!)?: ([\\w ])+([\\s\\S]*)"
- label: "breaking"
  title: "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\\([\\w\\-\\.]+\\))?!: ([\\w ])+([\\s\\S]*)"
