name: Auto-assignment

on:
  issues:
    types:
        - opened

jobs:
    assign_reviewers:
        runs-on: ubuntu-latest
        steps:
          - name: Check if issue has [Proposal] label
            id: check_proposal_label
            run: |
              echo "has_proposal_label=${{ contains(github.event.issue.title, 'proposal') }}" >> "$GITHUB_OUTPUT"
              category3=grep -e "Category" -A2 "${{ github.event.issue.body }}" | grep -v "Category" | grep "\S"
              echo "category=$category3" >> "$GITHUB_OUTPUT"
          - name: Run auto-assignment script
            if: ${{steps.check_proposal_label.outputs.has_proposal_label == 'true'}}
            run: echo "${{ steps.check_proposal_label.outputs.category }}"
