on:
  check_run:
    types: [completed]
    
jobs:
  check_run_test:
    runs-on: ubuntu-latest

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
    
    - name: Action is required
      if: github.event.check_run.name == 'DCO' && github.event.check_run.conclusion == 'action_required'
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: dco-required
        message: |
          Hey there and thank you for opening this pull request! 👋🏼

          Details:

          ```
          ${{ github.event.check_run.app.description }}
          ```
