on:
  check_run:
    types: [completed]
    
jobs:
  check_run_test:
    runs-on: ubuntu-latest

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
    
    - name: DCO Missing
      if: github.event.check_run.name == 'DCO' && github.event.check_run.conclusion == 'action_required'
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: dco-required
        number: ${{ github.event.check_run.check_suite.pull_requests[0].number }}
        message: |
          This project enforces the [Developer Certificate of Origin](https://developercertificate.org/) (DCO) on Pull Requests. That means all commit messages must contain the `Signed-off-by` line with an email address that matches the commit author.

          ${{ github.event.check_run.output.summary }}

    # Delete a previous comment when the issue has been resolved
    - name: DCO Found
      if: github.event.check_run.name == 'DCO' && github.event.check_run.conclusion != 'action_required'
      uses: marocchino/sticky-pull-request-comment@v2
      with:   
        header: dco-required
        number: ${{ github.event.check_run.check_suite.pull_requests[0].number }}
        delete: true
