on:
  check_run:
    types: [completed]
    
jobs:
  check_run_test:
    runs-on: ubuntu-latest

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
    
    - name: Action is required
      if: github.event.check_run.name == 'DCO' && github.event.check_run.conclusion == 'action_required'
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: dco-required
        number: ${{ github.event.check_run.check_suite.pull_requests[0].number }}
        message: |
          Hey there and thank you for opening this pull request! 👋🏼

          This App enforces the [Developer Certificate of Origin](https://developercertificate.org/) (DCO) on Pull Requests.
          It requires all commit messages to contain the `Signed-off-by` line with an email address that matches the commit author.
          
          The Developer Certificate of Origin (DCO) is a lightweight way for contributors to certify that they wrote or otherwise have the right to submit the code they are contributing to the project.
          Here is the full [text of the DCO](https://developercertificate.org/), reformatted for readability:
          
          > By making a contribution to this project, I certify that:\r\n>\r\n> 1. The contribution was created in whole or in part by me and I have the right to submit it under the open source license indicated in the file; or\r\n>\r\n> 2. The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the right under that license to submit that work with modifications, whether created in whole or in part by me, under the same open source license (unless I am permitted to submit under a different license), as indicated in the file; or\r\n>\r\n> 3. The contribution was provided directly to me by some other person who certified 1., 2. or 3. and I have not modified it.\r\n>\r\n> 4. I understand and agree that this project and the contribution are public and that a record of the contribution (including all personal information I submit with it, including my sign-off) is maintained indefinitely and may be redistributed consistent with this project or the open source license(s) involved.
          
          Contributors _sign-off_ that they adhere to these requirements by adding a `Signed-off-by` line to commit messages.
          
          ```
          This is my commit message
          
          Signed-off-by: Random J Developer <random@developer.example.org>
          ```
          
          Git even has a `-s` command line option to append this automatically to your commit message:
          
          ```
          $ git commit -s -m 'This is my commit message'
          ```          
          
          ${{ github.event.check_run.output.summary }}
