on:
  repository_dispatch:
    types: [on_demand_test]

env:
  ITEMS_TO_DEPLOY: '["test", "test3"]'

jobs:
  check_run_test:
    runs-on: ubuntu-latest

    steps:
    - name: Dump On Demand Payload
      env:
        PAYLOAD: ${{ toJson(github.event.client_payload) }}
      run: |
        echo "$PAYLOAD"

    - name: JavaScript Items to Deploy
      uses: actions/github-script@v6
      id: filter
      with:
        script: |
          const filter = JSON.parse(process.env.ITEMS_TO_DEPLOY);
          console.log(filter);
          // Grab from incoming payload
          const items = context.payload.client_payload.items;
          console.log(items);
          itemsToDeploy = items.filter(i => filter.includes(i));
          return itemsToDeploy;
          
    - name: JavaScript Should Deploy
      uses: actions/github-script@v6
      id: deploy
      env:
          ITEMS: '${{steps.filter.outputs.result}}'
      with:
        script: |
          const items = JSON.parse(process.env.ITEMS);
          console.log(items);
          return items.length > 0;
          
    - name: Get result
      run: echo "${{steps.filter.outputs.result}}"
    
    outputs:
      should_deploy: ${{ steps.deploy.outputs.result }}
      items_to_deploy: ${{ steps.filter.outputs.result }}

  release:
    needs: check_run_test
    runs-on: ubuntu-latest
    if: ${{ fromJSON(needs.check_run_test.outputs.should_deploy) }}
    strategy:
      matrix: 
        path: ${{ fromJSON(needs.check_run_test.outputs.items_to_deploy) }}
    steps:
      - name: Get result
        run: echo "I should deploy!"
    
