on:
  repository_dispatch:
    types: [on_demand_test]

jobs:
  check_run_test:
    runs-on: ubuntu-latest

    steps:
    - name: Dump On Demand Payload
      env:
        PAYLOAD: ${{ toJson(github.event.client_payload) }}
      run: |
        echo "$PAYLOAD"
