name: OFEP Status Check

on:
  pull_request:
    branches:
      - main

jobs:
   changed_files:
    runs-on: ubuntu-latest 
    name: Test added-OFEP proposals for status
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: ls
      - name: Get added files
        id: added-files
        uses: tj-actions/changed-files@v37
        with: 
          files: |
            **.md
      - run: ls
      - if: ${{ steps.added-files.outputs.added_files_count == 0 }}
        name: No check needed
        run: |
          echo "No OFEP proposals were added"
          exit 0
        
      - name: List all added files
        id: list-added-files
        if: ${{ steps.added-files.outputs.added_files_count > 0 }}
        run: |
          #!/bin/bash


          for file in ${{ steps.added-files.outputs.added_files }}; do
            while IFS= read -r line; do
              if [[ $line == "## State:"* ]]; then
                value=${line#*State:}
                value=${value# } # Remove leading whitespace
                if [[ "$value" != "REJECTED" && "$value" != "WITHDRAWN" && "$value" != "APPROVED" ]]; then
                  echo "Unmatched value detected in file: $file"
                  echo "Detected status: $value"
                  exit 1
                fi
              fi
            done < "$file"
          done

          echo "All files checked successfully."
          exit 0

      - if: ${{ steps.added-files.outputs.added_files_count > 0 && !contains(fromJSON('["REJECTED", "WITHDRAWN", "APPROVED"]'), steps.list-added-files.outputs.status) }}
        name: Exit with error
        run: |
          echo "${{ steps.list-added-files.outputs.status }}"
          echo "status is not approved"
          exit 1
