name: OFEP Status Check

on:
  pull_request_target:
    types:
      - opened
      - edited
      - closed
      - reopened
      # Makes sure we always add status check for PRs. Useful only if
      # this action is required to pass before merging. Otherwise, it
      # can be removed.
      - synchronize

jobs:
   changed_files:
    runs-on: ubuntu-latest 
    name: Test added-OFEP proposals for status
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get added files
        id: added-files
        uses: tj-actions/changed-files@v37
        with: 
          files: |
            **.md
      
      - if: ${{ steps.added-files.outputs.added_files_count == 0 }}
        name: No check needed
        run: |
          echo "No OFEP proposals were added"
          exit 0
        
      - name: List all added files
        id: list-added-files
        if: ${{ steps.added-files.outputs.added_files_count > 0 }}
        run: |
          for file in ${{ steps.added-files.outputs.added_files }}; do
            echo "$file was added"
            echo "status=$(grep -e "State" "$file" | tr -d "## State: " | tr -d '"')" >> "$GITHUB_OUTPUT"
          done

      - if: ${{ steps.added-files.outputs.added_files_count > 0 && !contains(fromJSON('["REJECTED", "WITHDRAWN", "APPROVED"]'), steps.list-added-files.outputs.status) }}
        name: Exit with error
        run: |
          echo "status is not approved"
          exit 1
